// Generated by LiveScript 1.4.0
(function(){
  var express, MongoClient, mongourl, ref$, app, getMongoDb, getCollection, logsurvey;
  express = require('express');
  MongoClient = require('mongodb').MongoClient;
  mongourl = (ref$ = process.env.MONGOHQ_URL) != null
    ? ref$
    : (ref$ = process.env.MONGOLAB_URI) != null
      ? ref$
      : (ref$ = process.env.MONGOSOUP_URL) != null ? ref$ : 'mongodb://localhost:27017/default';
  app = express();
  app.set('port', (ref$ = process.env.PORT) != null ? ref$ : 8080);
  app.use(express['static'](__dirname));
  app.use(require('body-parser').json());
  app.listen(app.get('port'), '0.0.0.0');
  app.get('/somefunc', function(req, res){
    return res.send('hello world');
  });
  app.post('/logsurvey', function(req, res){
    var data, surveyname;
    data = req.body;
    surveyname = data.surveyname;
    if (surveyname == null) {
      res.send('need surveyname param');
      return;
    }
    data.ip = req.ip;
    return logsurvey(data, function(){
      return res.send('done');
    });
  });
  app.get('/listsurvey', function(req, res){
    var surveyname;
    surveyname = req.query.surveyname;
    if (surveyname == null) {
      res.send('need surveyname param');
      return;
    }
    return getCollection(surveyname, function(collection, db){
      return collection.find({}).toArray(function(err, results){
        res.send(JSON.stringify(results));
        return db.close();
      });
    });
  });
  getMongoDb = function(callback){
    return MongoClient.connect(mongourl, function(err, db){
      if (err) {
        return console.log('error getting mongodb');
      } else {
        return callback(db);
      }
    });
  };
  getCollection = function(collection_name, callback){
    return getMongoDb(function(db){
      return callback(db.collection(collection_name), db);
    });
  };
  logsurvey = function(data, callback){
    var surveyname;
    surveyname = data.surveyname;
    if (surveyname == null) {
      console.log('missing surveyname');
      return;
    }
    data.time = Date.now();
    data.localtime = new Date().toString();
    console.log('performing insertion');
    console.log(data);
    return getCollection(surveyname, function(collection, db){
      console.log('have collection:');
      console.log(collection);
      return collection.insert(data, function(err, docs){
        if (err != null) {
          console.log('error upon insertion');
          console.log(err);
        } else {
          console.log('insertion done');
          if (callback != null) {
            callback();
          }
        }
        return db.close();
      });
    });
  };
}).call(this);
